version: 2.1
orbs:
  react-native: react-native-community/react-native@5.1.0

jobs:
  test-and-build:
    docker:
      - image: react-native
    steps:
      - run:
          name: test and build
          command: |
            yarn
            yarn run test
            yarn run compile

workflows:
  node-tests:
    jobs:
      - test-and-build
