version: 2.1
orbs:
  rn: react-native-community/react-native@5.1.0

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  test-and-build:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Jest
          command: yarn jest
      - run:
          name: Compile
          command: yarn run compile

workflows:
  node-tests:
    jobs:
      - checkout_code
      - test-and-build:
          requires:
            - checkout_code
